version: '3'

services:

  mysql-dev:
    image: mysql:8.0.2
    restart: always 
    environment:
      MYSQL_DATABASE: 'db_foodtruck'
      MYSQL_USER: 'springUser'
      MYSQL_ROOT_PASSWORD: 'springUser!'
      MYSQL_PASSWORD: 'springUser!'
    ports:
      - '3308:3306'

  client:
    image: mysql:8.0.2
    depends_on:
      - mysql-dev
    command: mysql -uroot -ppassword -hmysql-dev db_foodtruck 
