version: '3.3'
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always 
    environment:
      MYSQL_DATABASE: 'db_foodtruck'
      MYSQL_ROOT_PASSWORD: 'springUser'
      MYSQL_ROOT_HOST: 'springUser!'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
